/*
 * generated by Xtext 2.21.0
 */
package io.tokilabs.ide

import com.google.inject.Guice
import io.tokilabs.DISLRuntimeModule
import io.tokilabs.DISLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DISLIdeSetup extends DISLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DISLRuntimeModule, new DISLIdeModule))
	}
	
}
