/*
 * generated by Xtext 2.21.0
 */
package io.tokilabs


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DISLRuntimeModule extends AbstractDISLRuntimeModule {
}
