/*
 * generated by Xtext 2.21.0
 */
package io.tokilabs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DISLStandaloneSetup extends DISLStandaloneSetupGenerated {

	def static void doSetup() {
		new DISLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
